//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/4/2021 10:36:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace com.pizzaworld.Orders
{
    public partial class Stores {

        public Stores()
        {
            OnCreated();
        }

        public virtual string Address { get; set; }

        public virtual short StoreNo { get; set; }

        public virtual string Name { get; set; }

        public virtual DateTime ordertime { get; set; }

        public virtual Order Order { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
