//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 1/4/2021 10:36:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace com.pizzaworld.Orders
{
    public enum Toppings : int
    {
        Anchovies,
        Mushroom,
        GreenPepper,
        pineapple,
        pepperoni,
        Beef
    }
}
